language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6

install:
  - pip install -U pip
  - pip install -U pyflakes

script:
  # Static analysis
  - pyflakes .

  # Test install
  - python setup.py install
